### ISSUE TITLE
Rotations: Why PRY and not RPY convention?

### ISSUE THREAD

**Issue by SiggiGue** [AudioSceneDescriptionFormat/asdf#5]
In the documentation of ASDF following convention is mentioned:

Azimuth (Yaw) : z-axis
Elevation (Pitch) : x-axis
Roll : y-axis
-> PRY convention
As far as I know, this is a rather unusual convention. 

I thought RPY is the usual convention:
Roll : x
Pitch : y
Yaw : z

Is there a reason for the PRY convention? And are there pros and cons from your perspective?
Thank you.

**Comment by mgeier** [comment]
I've tried to motivate my choice here: https://audioscenedescriptionformat.readthedocs.io/position-orientation.html, does that make sense?

If I draw a few points on a piece of paper, I feel most comfortable obtaining their coordinates if the x-axis points to the right and the y-axis points to the upper edge of the paper.
However, this only really works if your main "view" direction (which I would consider the zero-azimuth direction) is along the positive y-axis.
Because a listener with an azimuth of zero should hear a positive x-coordinate from the right.

I think I would choose this convention in the 2D case, and I see no reason why not to use it in the 3D case as well.

When using RPY, where would you make the z-axis point to?

AFAIK, in aeronautics, the z-axis typically points down, which to me seems quite un-intuitive for our use case.

However, if the z-axis points up (which seems natural to me) and if a right-handed system is to be used (which seems to be the only sane choice), then the pitch angle is negative when the nose is pointing up, which also seems un-intuitive to me.

Just as I think that moving up should increase the z-coordinate, pitching up should increase the elevation angle.

Apart from being more or less usual, what do you think are the pros and cons?

**Comment by SiggiGue** [comment]
OK, thanks for clarification. 

Until now, I was used to having the x axis as front vector, y as left and z as up ( right hand rule: x=forefinger, y=long finger, z: thumb).
From the 2D perspective the angle convention in the unit circle is 0° at (1, 0) and not (0, 1). Sticking to this rule would lead to az = el = 0 being (1,0,0) in the unit sphere.
But maybe there are no pros and cons at all.
In the end it is only about a consistent convention.

**Comment by mgeier** [comment]
> Until now, I was used to having the x axis as front vector, y as left and z as up ( right hand rule: x=forefinger, y=long finger, z: thumb).

Wow, that's interesting, I was taught a different right hand rule!

The way I was told is where the order of fingers matches the order of axes (very easy to remember):

1. x: thumb
2. y: index f.
3. z: middle f.

In the end both work the same, but I could never remember the order of your rule. It seems arbitrary (because I guess it is?).

The one I learned can be seen on the Swiss banknote here: https://en.wikipedia.org/wiki/Right-hand_rule

> From the 2D perspective the angle convention in the unit circle is 0° at (1, 0) and not (0, 1).

Yes, that seems reasonable.

This is basically the typical 2D-plot coordinate system rotated counterclockwise by 90°, if I understand you correctly.

I guess it would be easy enough to use, but I somewhat prefer to use the un-rotated system where x is to the right and y is up (= towards the top edge of a piece of paper).

> Sticking to this rule would lead to az = el = 0 being (1,0,0) in the unit sphere.

Yes, that part sounds desirable, but with your system a positive "elevation" would mean that you point your nose downwards.

And I would very much like a positive elevation to mean "pitch up".

> But maybe there are no pros and cons at all. In the end it is only about a consistent convention.

Yes, there will always be different systems, and we should be prepared to convert between them. But I do think there are pros and cons, with different importance to different people.

If you are fine with z pointing down, RPY is great.
If you want z pointing up, but you are fine with elevation pitching down, RPY is also great.

I just happen to not want any of those two.

BTW, on this page I'm trying to make the axes and rotation angles very clear, I hope I succeeded: https://audioscenedescriptionformat.readthedocs.io/en/latest/rotation-matrices.html

**Comment by SiggiGue** [comment]
> > Until now, I was used to having the x axis as front vector, y as left and z as up ( right hand rule: x=forefinger, y=long finger, z: thumb).
> 
> Wow, that's interesting, I was taught a different right hand rule!
> 
> The way I was told is where the order of fingers matches the order of axes (very easy to remember):
> 
>     1. x: thumb
> 
>     2. y: index f.
> 
>     3. z: middle f.
> 
> 
> In the end both work the same, but I could never remember the order of your rule. It seems arbitrary (because I guess it is?).
> 
> The one I learned can be seen on the Swiss banknote here: https://en.wikipedia.org/wiki/Right-hand_rule

Just citing exactly from your linked article: 

  _"The sequence is often: index finger, middle finger, thumb. Two other sequences also work because they preserve the cycle:
     Middle finger, thumb, index finger.
    Thumb, index finger, middle finger (e.g., see the ninth series of the [Swiss 200-francs banknote](https://en.wikipedia.org/wiki/Banknotes_of_the_Swiss_franc#Ninth_series)).[[citation needed](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)]"_

> 
> > From the 2D perspective the angle convention in the unit circle is 0° at (1, 0) and not (0, 1).
> 
> Yes, that seems reasonable.
> 
> This is basically the typical 2D-plot coordinate system rotated counterclockwise by 90°, if I understand you correctly.
> 
> I guess it would be easy enough to use, but I somewhat prefer to use the un-rotated system where x is to the right and y is up (= towards the top edge of a piece of paper).
> 
> > Sticking to this rule would lead to az = el = 0 being (1,0,0) in the unit sphere.
> 
> Yes, that part sounds desirable, but with your system a positive "elevation" would mean that you point your nose downwards.
> 

OK, now I understand your points. This is really motivated from the polar coordinates with az 0..2pi and el +-pi/2 and sounds reasonable from that perspective.
Thank you.
